---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: graph-bot
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: graph-bot
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
# Python Service
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: graph-bot
  labels:
    app: python-service
spec:
  selector:
    app: python-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
# Ollama Service
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: graph-bot
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
  - name: http
    port: 11434
    targetPort: 11434
    protocol: TCP
  type: ClusterIP
---
# Frontend LoadBalancer (External Access)
apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: graph-bot
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  type: NodePort
